implmenting the Add-remove books features
HSMathebula/Awesome-books-plain-JavaScript-with-objects pull request #1
Opened 2022-04-25 17:14 UTC by khitermedachraf

### In this mini-project, we implement the following features:

- Create a collection that keeps a list of books

- Create a function to add a new book to the collection

- Create a function to remove a book from the collection.

- Display all books saved in the collection in the top part of the page.

- Make sure that data is preserved in the browser's memory by using [localStorage]

2022-04-25 17:29 UTC, Wes-Isaac requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-25 17:29 UTC, Wes-Isaac commented on style.css
> +}
- [ ] Great job so far, it's one of the project requirements to use the style that matches the wireframe. Kindly add styling to your site.
- [ ] **Great job using Microverse's template for your readme but you didn't customize it to this particular project please do that.**

## Wireframe

![image](https://user-images.githubusercontent.com/59416136/165141884-e81c2de4-9ca1-433f-aab7-35a4a6a6ac0a.png)

2022-04-25 17:41 UTC, BenMukebo requested changes
....

2022-04-26 10:08 UTC, mikethreels approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 10:14 UTC, merged

2022-04-26 10:16 UTC, t-yanick reviewed
Hi @HSMathebula, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._